# Generated by Django 5.2.8 on 2025-11-19 13:26

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projeto",
            name="data_inicio",
        ),
        migrations.RemoveField(
            model_name="responsavel",
            name="tarefa",
        ),
        migrations.RemoveField(
            model_name="tarefa",
            name="concluida",
        ),
        migrations.AddField(
            model_name="projeto",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="projeto",
            name="data_criacao",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 11, 19, 13, 26, 28, 703035, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="responsavel",
            name="telefone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="tarefa",
            name="data_conclusao",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tarefa",
            name="data_criacao",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tarefa",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tarefa",
            name="responsavel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tarefas",
                to="api.responsavel",
            ),
        ),
        migrations.AddField(
            model_name="tarefa",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("em_andamento", "Em Andamento"),
                    ("concluida", "Concluída"),
                ],
                default="pendente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="nome",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="responsavel",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="responsavel",
            name="nome",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="titulo",
            field=models.CharField(max_length=200),
        ),
    ]
